# Технические средства анализа данных

<a href="https://www.anaconda.com/distribution/">Anaconda distribution</a>
<br /><br />
<a href="https://www.jetbrains.com/pycharm/">PyCharm</a> - main IDE for our course
<br /><br />
<a href="https://numpy.org/">Numpy documentation</a><br />
<a href="https://scikit-learn.org/stable/">sklearn documentation</a><br />
<a href="https://opencv.org/">OpenCV documentation</a><br />
<a href="https://matplotlib.org/">Matplotlib documentation</a>

### Дополнительные материалы:
<a href="https://stackoverflow.com/">Stackoverflow</a><br />
<a href="http://pythontutor.ru/">pythontutor online</a><br />
<a href="https://snakify.org/">snakify</a><br />
<a href="https://www.coursera.org/search?query=python">Coursera Python courses</a><br />

## Управление порядком исполнения (control flow)

In [76]:
# Условный оператор

today = 'snowing'

if today == 'raining':
    print('sad :(')
elif today == 'sunny':
    print('YEY!')
else:
    print('what`s going on?')

what`s going on?


In [67]:
# Генератор
a = range(1,10,2)
print(a)

range(1, 10, 2)


In [68]:
type(a)

range

In [71]:
dir(a)

['__bool__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index',
 'start',
 'step',
 'stop']

In [72]:
# Циклы

for i in a:
    print(i)

1
3
5
7
9


In [73]:
for i in [2,4,5,7,8,'me','and','you']:
    print(i)

2
4
5
7
8
me
and
you


In [75]:
for i in [2,4,'me',5,7,8,'me','and','you']:
    print(i)
    if i >= 5:
        break

2
4
me


TypeError: '>=' not supported between instances of 'str' and 'int'

In [74]:
for i in [2,'me',4,5,7,8,'and','you']:
    if type(i) == str:
        continue
    
    print(i)
    

2
skipping strings
4
5
7
8
skipping strings
skipping strings


In [79]:
# Функции

def some_name(arg):
    print(arg)
    return 0

In [80]:
some_name('we are the champions!')

we are the champions!


0

In [85]:
# Еще один генератор

def datagen(max_value = 121):
    a = [i for i in range(max_value)]
    idx = 0
    while True:
        yield a[idx]
        idx = idx + 1

In [86]:
gen = datagen(7)

In [87]:
while True:
    print(next(gen))

0
1
2
3
4
5
6


IndexError: list index out of range

### Обработка исключений

In [96]:
# Еще один генератор - с обработкой исключения

def datagen(max_value = 121):
    a = [i for i in range(max_value)]
    idx = 0
    while True:
        value = None
        try:
            value = a[idx]
        except:
            raise StopIteration()
        yield value
        idx = idx + 1

In [97]:
gen2 = datagen(5)
while True:
    try:
        new_value = next(gen2)
        print(new_value)
    except:
        break

0
1
2
3
4


### map, lambda-функции и list comprehensions

#### list comprehensions - вычисления на списках

In [103]:
[x for x in range(1,5,2)]

[1, 3]

In [105]:
import math
[math.pow(d, p) for (d,p) in zip([2,4,8,16,32,64,128], [1,1/2,1/3,1/4,1/5,1/6,1/7])]

[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

In [98]:
def sqr(x):
    return x**2

In [107]:
a = range(10)

#### map - применение функции ко всем элементам перечислимого аргумента

In [110]:
map(sqr, a)

In [109]:
[d for d in map(sqr, a)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

#### lambda-функции

In [111]:
[d for d in map(lambda x: x**2, a)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [112]:
import numpy as np

In [156]:
dot = lambda x,theta: sum([x[i]*theta[i] for i in range(len(x))])

In [149]:
x = np.array([[1., 22.],[1., 25.],[1., 34.]])
x

array([[ 1., 22.],
       [ 1., 25.],
       [ 1., 34.]])

In [150]:
x.shape

(3, 2)

In [151]:
theta = np.array([[3.],[28.]])

In [152]:
theta.shape

(2, 1)

In [157]:
[dot(x[i], np.squeeze(theta)) for i in range(x.shape[0])]

[619.0, 703.0, 955.0]

## Векторизация векторных и матричных операций с помощью <a href="https://numpy.org/">numpy</a>

In [132]:
np.dot(x, theta)

array([[619.],
       [703.],
       [955.]])

In [158]:
X = np.random.randn(100,2)
X.shape

(100, 2)

In [159]:
X

array([[-4.23374716e-01, -3.31784910e-02],
       [-4.79318471e-01, -2.09823324e+00],
       [ 8.44224845e-01,  7.28957659e-01],
       [ 1.18364704e+00, -1.02227837e+00],
       [ 2.08816500e-01,  1.02433331e+00],
       [ 5.16119482e-01,  2.26578885e+00],
       [-7.21193341e-01,  8.74932782e-01],
       [ 1.68517708e+00,  6.09242464e-01],
       [ 1.26093036e-01,  2.77644981e-01],
       [ 9.53649579e-01,  1.29996114e+00],
       [ 1.15285127e+00,  8.07802807e-01],
       [-7.76264362e-01, -7.93068759e-01],
       [-3.32370118e-01, -5.01306013e-01],
       [ 5.19785150e-01, -2.27511222e+00],
       [ 1.15122050e-01,  5.06424001e-02],
       [ 9.71269633e-01,  9.34554860e-01],
       [-1.27390845e+00,  1.72002997e+00],
       [-3.45911954e+00, -9.83553994e-01],
       [-9.00628438e-01, -6.11582671e-01],
       [ 1.09018490e+00,  1.38752517e+00],
       [-1.72066761e+00, -1.77406788e+00],
       [-3.97607847e-01,  3.12790048e-01],
       [ 9.15566201e-01, -4.44009704e-01],
       [-7.

In [161]:
dot_product_1 = [dot(X[i], np.squeeze(theta)) for i in range(X.shape[0])]
dot_product_1

[-2.199121898162047,
 -60.188486198512415,
 22.943488980687263,
 -25.07285315918726,
 29.307782217662858,
 64.99044615595702,
 22.334537865938884,
 22.11432022178419,
 8.15233857294222,
 39.2598607610719,
 26.077032388057255,
 -24.534718348187678,
 -15.03367871027654,
 -62.14378676159749,
 1.7633533537289376,
 29.0813449814344,
 44.33911376526826,
 -37.91687047036702,
 -19.82620011069234,
 42.121259494153065,
 -54.83590343576185,
 7.56529781203411,
 -9.685573098202065,
 7.504333787120676,
 -2.117757159422991,
 50.24933388864885,
 -40.89424467977505,
 -15.598944511104033,
 2.263302330307985,
 24.445643460200454,
 -12.085114269090635,
 44.46684622928309,
 -34.72468437147677,
 -66.530539883206,
 21.58762655921662,
 5.544828270089969,
 -34.39867185107965,
 22.911177057893802,
 19.323666353139163,
 -37.5046998343018,
 -25.085311882194166,
 28.95207305021888,
 -22.49660030738028,
 0.41371629626532647,
 -11.296033179178576,
 18.502634594501796,
 -27.9882937167401,
 51.60870756689482,
 38.7481

In [162]:
dot_product_2 = np.dot(X, theta)

In [163]:
dot_product_2

array([[ -2.1991219 ],
       [-60.1884862 ],
       [ 22.94348898],
       [-25.07285316],
       [ 29.30778222],
       [ 64.99044616],
       [ 22.33453787],
       [ 22.11432022],
       [  8.15233857],
       [ 39.25986076],
       [ 26.07703239],
       [-24.53471835],
       [-15.03367871],
       [-62.14378676],
       [  1.76335335],
       [ 29.08134498],
       [ 44.33911377],
       [-37.91687047],
       [-19.82620011],
       [ 42.12125949],
       [-54.83590344],
       [  7.56529781],
       [ -9.6855731 ],
       [  7.50433379],
       [ -2.11775716],
       [ 50.24933389],
       [-40.89424468],
       [-15.59894451],
       [  2.26330233],
       [ 24.44564346],
       [-12.08511427],
       [ 44.46684623],
       [-34.72468437],
       [-66.53053988],
       [ 21.58762656],
       [  5.54482827],
       [-34.39867185],
       [ 22.91117706],
       [ 19.32366635],
       [-37.50469983],
       [-25.08531188],
       [ 28.95207305],
       [-22.49660031],
       [  0

In [166]:
dot_product_2[0] - dot_product_1[0]

array([0.])

In [165]:
[dot_product_2[i] - dot_product_1[i] for i in range(len(dot_product_1))]

[array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array

## В чем разница?!

замерим время исполнения

In [169]:
%timeit dot_product_1 = [dot(X[i], np.squeeze(theta)) for i in range(X.shape[0])]

265 µs ± 7.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [170]:
%timeit dot_product_2 = np.dot(X, theta)

813 ns ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Векторизация - ОБЯЗАТЕЛЬНЫЙ способ ускорения вычислений!